abbrev-alias -g A="| awk '{}'"
abbrev-alias -g S="| sed -E 's///g'"
abbrev-alias -g G="| grep -E "
abbrev-alias -g L="| less"
abbrev-alias -g H="HEAD"
abbrev-alias -f B="git symbolic-ref --short HEAD"
